---
# Uncomment the below if you want to run this playbook individually.
#- hosts: ansible-freebsd-server
#  gather_facts: false
#  remote_user: ansible
#  become: yes
#  tasks:

- name: install ntp
  pkgng:
    name: ntp
    state: present

- name: copy default ntp.conf
  template:
    src: '../template/etc/ntp.conf'
    dest: '/etc/ntp.conf'
        
- name: sync ntp
  raw: ntpdate ntp.is.co.za
