---
- hosts: ansible-freebsd-server
  gather_facts: false
  remote_user: ansible
  become_method: su
  become: yes

  roles:
   - bootstrap
   - update
   - miscinstalls
   - ntpd
   - pf
   - rc
   - ossec-client
