# Always start anible playbook with three dashes.
---
# specify remote host
- hosts: ansible-test-server
# specify remote user (make sure your ssh key is copied onto the remote host / user)
  remote_user: root
# modules
  tasks:
       - name: Create file
         file: path=/tmp/guava state=touch